micronaut:
  application:
    name: demo

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    # Nota occorre sempre definire un db di collegamento
    url: jdbc:mysql://localhost:3306/masterdata
    driverClassName: com.mysql.cj.jdbc.Driver
    username: test
    password: pwciaociao
    schema-generate: NONE
    dialect: MYSQL

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true